// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-professional-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_professional_profile_default = defineTool({
  name: "get_professional_profile",
  title: "Get professional profile",
  description: "Return Ileana Mazilu's professional profile: name, headline, contact info, LinkedIn, availability, and a short bio for Senior Medical Writing / regulatory work.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Ileana Mazilu",
      headline: "Senior Medical Writer & Regulatory Consultant",
      email: "maziluileana88@gmail.com",
      phone: "+40 766 687 508",
      linkedin: "https://www.linkedin.com/in/ileana-mazilu-aa211181",
      availability: "Available for Senior Medical Writing Consultations",
      bio: "Senior Medical Writer with 80+ regulatory submissions across 12+ therapeutic areas, specializing in Class III Clinical Evaluation Reports (CERs), MDCG 2020-aligned literature search protocols, benefit-risk analysis, and AI-assisted regulatory workflows.",
      website: "https://ileana-mazilu.lovable.app"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List consulting services",
  description: "List the medical writing and regulatory consulting services Ileana Mazilu offers, including CERs, literature search protocols, and AI-assisted compliance review.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const services = [
      {
        id: "clinical-evaluation-reports",
        name: "Clinical Evaluation Reports (CERs)",
        description: "MDR-compliant Class II/III CERs, including data appraisal, benefit-risk analysis, and post-market surveillance integration."
      },
      {
        id: "literature-search-protocols",
        name: "Literature Search Protocols",
        description: "PubMed / Embase search strings and inclusion/exclusion criteria aligned with MDCG 2020-13 guidelines."
      },
      {
        id: "regulatory-submissions",
        name: "Regulatory Submissions",
        description: "Technical documentation and dossier authoring for EU MDR, FDA, and EUDAMED submissions across 12+ therapeutic areas."
      },
      {
        id: "medad-compliance-ai",
        name: "MedAd Compliance AI",
        description: "AI-powered medical advertising compliance auditing with medical-writer-verified guardrails for FDA and EU MDR frameworks."
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
      structuredContent: { services }
    };
  }
});

// src/lib/mcp/tools/list-therapeutic-areas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_therapeutic_areas_default = defineTool3({
  name: "list_therapeutic_areas",
  title: "List therapeutic areas",
  description: "List the 12+ therapeutic areas Ileana Mazilu has covered across 80+ regulatory submissions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const areas = [
      "Oncology",
      "Cardiovascular",
      "Neurology",
      "Orthopedics",
      "Gynecology",
      "Ophthalmology",
      "AI-Diagnostics",
      "Endocrinology",
      "Dermatology",
      "Respiratory",
      "Gastroenterology",
      "Urology"
    ];
    return {
      content: [
        {
          type: "text",
          text: `Therapeutic areas covered (${areas.length}):
- ${areas.join("\n- ")}`
        }
      ],
      structuredContent: { areas, count: areas.length }
    };
  }
});

// src/lib/mcp/tools/request-consultation.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var request_consultation_default = defineTool4({
  name: "request_consultation",
  title: "Request a consultation",
  description: "Generate a pre-filled mailto link the caller can use to reach Ileana Mazilu about a specific medical writing or regulatory consulting need.",
  inputSchema: {
    topic: z.string().min(3).max(200).describe("Short topic or subject line for the consultation request."),
    details: z.string().max(2e3).optional().describe("Optional additional context (project type, timeline, therapeutic area).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topic, details }) => {
    const email = "maziluileana88@gmail.com";
    const subject = encodeURIComponent(`Consultation request: ${topic}`);
    const body = encodeURIComponent(
      details ?? "Hello Ileana,\n\nI would like to discuss a potential consultation.\n\nThank you."
    );
    const mailto = `mailto:${email}?subject=${subject}&body=${body}`;
    return {
      content: [
        {
          type: "text",
          text: `To request a consultation, email ${email} or open:
${mailto}`
        }
      ],
      structuredContent: { email, mailto, topic }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ileana-mazilu-portfolio-mcp",
  title: "Ileana Mazilu Portfolio MCP",
  version: "0.1.0",
  instructions: "Public MCP server exposing Ileana Mazilu's Senior Medical Writing portfolio: professional profile, consulting services, therapeutic-area coverage, and a helper to draft consultation requests. All data is public portfolio information.",
  tools: [get_professional_profile_default, list_services_default, list_therapeutic_areas_default, request_consultation_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
